### ISSUE TITLE
unmarshal error with credstash saved secrets

### ISSUE THREAD

**Issue by captn3m0** [Versent/unicreds#75] opened 2017-11-28 14:52 UTC
<summary>
We face the following error:
<details>

```
credstash --region ap-south-1 --table credstash-prod-app get password
<secret>
unicreds --region ap-south-1 --table credstash-prod-app get password --debug
   • Configure AWS             profile= region=ap-south-1
   • Getting highest version secret
   ⨯ failed                    error=UnmarshalTypeError: cannot unmarshal binary into Go value of type string
```
</details>

`list` seems to work fine:
```
./unicreds --region ap-south-1 --table=credstash-prod-app list
+----------------------+---------------------+---------------+
|         NAME         |       VERSION       |  CREATED-AT   |
+----------------------+---------------------+---------------+
| password             | 0000000000000000000 | Not Available |
```

I've tried it with secrets having Version>0, and it still does not work and give the same error. Secrets have been stored using credstash.

**Comment by captn3m0** [comment] 2017-12-06 13:09
@wolfeidau Any chance this is a known issue/has a workaround?

**Comment by aerostitch** [comment] 2018-03-27 21:35
I'm facing the same issue after switching to the latest version of credstash.
The issue is that now the hmac is stored as a binary entry whith a sha256 digest when before it was a string.
I guess the issue is similar here (I'm using custom code, not the command-line directly). I'll try to push a PR today to address that issue.

**Comment by wolfeidau** [comment] 2018-03-27 21:52
I would love to get this fixed so I can do a release with the other PRs I merged today.

Ping me if you need anything.

**Comment by aerostitch** [comment] 2018-03-27 22:42
I'm almost done with the PR.

**Comment by aerostitch** [comment] 2018-03-27 23:12
PR pushed

**Closed** 2018-03-27 23:42 UTC
